options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_VERSION: '1-0-0'
  _ZONE: asia-east1-b

steps:
  - name: 'hashicorp/packer'
    dir: images/ubuntu/tomcat
    args: ['init', 'image.pkr.hcl']

  - name: 'hashicorp/packer'
    dir: images/ubuntu/tomcat
    args:
      - build
      - '-var=image_version=${_IMAGE_VERSION}'
      - '-var=zone=${_ZONE}'
      - '-var=git_sha=${COMMIT_SHA}'
      - 'image.pkr.hcl'
