options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_VERSION: '1-0-0'

steps:
  - name: 'hashicorp/packer'
    args: ['init', 'images/ubuntu/tomcat/image.pkr.hcl']

  - name: 'hashicorp/packer'
    args:
      - validate
      - '-var=image_version=${_IMAGE_VERSION}'
      - '-var=git_sha=${COMMIT_SHA}'
      - 'images/ubuntu/variables.pkr.hcl'
      - 'images/ubuntu/tomcat/image.pkr.hcl'

  - name: 'hashicorp/packer'
    args:
      - build
      - '-var=image_version=${_IMAGE_VERSION}'
      - '-var=git_sha=${COMMIT_SHA}'
      - 'images/ubuntu/variables.pkr.hcl'
      - 'images/ubuntu/tomcat/image.pkr.hcl'
